include: package:very_good_analysis/analysis_options.9.0.0.yaml

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    prefer_const_constructors: false
    one_member_abstracts: false
