name: dart_model_converter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  tabler_icons: ^2.5.0+1
  flutter_code_editor: ^0.3.2
  dart_style: ^2.3.7
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  analyzer: ^6.7.0
  code_builder: ^4.10.1
  change_case: ^2.1.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

dev_dependencies:
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
